"""mkchamber.py — the Mode 7 gravity chamber: tiles, palette, map, attrs.

Mode 7 is its own data world (8bpp linear 64-byte tiles, a 128x128 byte map
interleaved into VRAM $0000-$3FFF words) — tmx2snes doesn't speak it, so the
chamber pipeline is this generator (DECISIONS: Phase 3 checkpoint).

Authoring: assets/maps/chamber01.txt — 32x32 metatile ASCII grid, one char =
one 16x16 metatile = a 2x2 quad of 8x8 tiles, centered at tile (32,32) of
the 128x128 map (the rest is void). Legend below.

Outputs into src/data/generated/: chamber.chr (8bpp tiles), chamber.pal
(colors 0-127 ONLY — sprites own 128-255, INV-HW-006), chamber.map.bin
(16384 bytes), chamber.att.bin (256 attr words, low=collision high=material),
chamber.h (checksum + spawn), chamber_preview.png. Deterministic.
"""
import os
import struct
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__)))
from mktiles import bgr555, write_png  # noqa: E402

ROOT = os.path.join(os.path.dirname(__file__), "..", "..")
GEN = os.path.join(ROOT, "src", "data", "generated")
TXT = os.path.join(ROOT, "assets", "maps", "chamber01.txt")

# chamber palette, indices 0-15 (of the 0-127 tile half)
PAL = [
    0x060810,  # 0 void/backdrop
    0x101018,  # 1 outline
    0x232C40,  # 2 slate dark
    0x3A4A66,  # 3 slate mid
    0x55688C,  # 4 slate light
    0x7C90B2,  # 5 slate highlight
    0x3A2E1E,  # 6 brass shadow
    0x7A5A22,  # 7 brass mid
    0xB08A30,  # 8 brass light
    0xE0C060,  # 9 brass highlight
    0x1E2A26,  # 10 accent dark
    0x35514A,  # 11 accent green
    0xC7D4E8,  # 12 bright edge
    0x804060,  # 13 spare
    0x442222,  # 14 spare
    0x000000,  # 15 spare
]

COL_SOLID = 0x01
MAT_BRASS = 0x01 << 8


class M16:
    def __init__(self, fill=0):
        self.p = [[fill] * 16 for _ in range(16)]

    def rect(self, x0, y0, x1, y1, c):
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                if 0 <= x < 16 and 0 <= y < 16:
                    self.p[y][x] = c

    def quads(self):
        out = []
        for oy in (0, 8):
            for ox in (0, 8):
                out.append([[self.p[oy + y][ox + x] for x in range(8)]
                            for y in range(8)])
        return out


def mt_wall():
    # rotation-neutral slate panel: symmetric grid + center rivet
    c = M16(3)
    c.rect(0, 0, 15, 0, 4)
    c.rect(0, 15, 15, 15, 2)
    c.rect(0, 0, 0, 15, 4)
    c.rect(15, 0, 15, 15, 2)
    c.rect(7, 1, 8, 14, 2)
    c.rect(1, 7, 14, 8, 2)
    c.rect(7, 7, 8, 8, 5)
    return c


def mt_brass():
    c = M16(7)
    c.rect(0, 0, 15, 0, 9)
    c.rect(0, 15, 15, 15, 6)
    c.rect(0, 0, 0, 15, 9)
    c.rect(15, 0, 15, 15, 6)
    c.rect(3, 3, 12, 12, 8)
    c.rect(7, 7, 8, 8, 9)
    return c


def mt_ledge():
    c = M16(2)
    c.rect(0, 0, 15, 1, 5)
    c.rect(0, 14, 15, 15, 1)
    c.rect(4, 6, 11, 9, 3)
    return c


# tile 0 = void; then 4 tiles per metatile in this order
METAS = [("wall", mt_wall(), COL_SOLID),
         ("brass", mt_brass(), COL_SOLID | MAT_BRASS),
         ("ledge", mt_ledge(), COL_SOLID)]
LEGEND = {".": None, "#": 0, "B": 1, "=": 2}


def main():
    os.makedirs(GEN, exist_ok=True)
    tiles = [[[0] * 8 for _ in range(8)]]  # tile 0: void
    attrs = [0]
    for _, canvas, attr in METAS:
        for t in canvas.quads():
            tiles.append(t)
            attrs.append(attr)
    attrs += [0] * (256 - len(attrs))

    lines = [ln.rstrip("\n") for ln in open(TXT) if ln.strip("\n") != ""]
    assert len(lines) == 32, len(lines)
    m = [[0] * 128 for _ in range(128)]
    for my, ln in enumerate(lines):
        assert len(ln) == 32, (my, len(ln))
        for mx, ch in enumerate(ln):
            mi = LEGEND[ch]
            if mi is None:
                continue
            base = 1 + mi * 4
            ty, tx = 32 + my * 2, 32 + mx * 2
            m[ty][tx] = base
            m[ty][tx + 1] = base + 1
            m[ty + 1][tx] = base + 2
            m[ty + 1][tx + 1] = base + 3

    with open(os.path.join(GEN, "chamber.chr"), "wb") as f:
        for t in tiles:
            for row in t:
                f.write(bytes(row))  # 8bpp linear, 64 bytes/tile
    with open(os.path.join(GEN, "chamber.pal"), "wb") as f:
        for i in range(128):
            f.write(struct.pack("<H", bgr555(PAL[i]) if i < len(PAL) else 0))
    mapbytes = bytes(b for row in m for b in row)
    with open(os.path.join(GEN, "chamber.map.bin"), "wb") as f:
        f.write(mapbytes)
    with open(os.path.join(GEN, "chamber.att.bin"), "wb") as f:
        f.write(struct.pack("<256H", *attrs))

    ck = 0
    for b in mapbytes:
        ck = (ck + b) & 0xFFFF
    for a in attrs:
        ck = (ck + a) & 0xFFFF
    with open(os.path.join(GEN, "chamber.h"), "w", newline="\n") as f:
        f.write("/* GENERATED by tools/art/mkchamber.py — never hand-edit. */\n")
        f.write("#ifndef GEN_CHAMBER_H\n#define GEN_CHAMBER_H\n")
        f.write("#define CHAM_CKSUM 0x%04X\n" % ck)
        f.write("#define CHAM_TILES %d\n" % len(tiles))
        f.write("#endif\n")
    with open(os.path.join(GEN, "chamber.asm"), "w", newline="\n") as f:
        f.write('.include "hdr.asm"\n\n')
        f.write("; GENERATED by tools/art/mkchamber.py — never hand-edit.\n")
        f.write('.section ".chamber" superfree\n')
        f.write('cham_chr:\n.incbin "src/data/generated/chamber.chr"\n')
        f.write('cham_chr_end:\n')
        f.write('cham_pal:\n.incbin "src/data/generated/chamber.pal"\n')
        f.write('cham_map:\n.incbin "src/data/generated/chamber.map.bin"\n')
        f.write('cham_att:\n.incbin "src/data/generated/chamber.att.bin"\n')
        f.write(".ends\n")

    # preview: the center 64x64-tile area at 1px/px
    rows = []
    for ty in range(32, 96):
        for py in range(8):
            row = bytearray()
            for tx in range(32, 96):
                t = tiles[m[ty][tx]]
                for px in range(8):
                    v = PAL[t[py][px]]
                    row += bytes(((v >> 16) & 0xFF, (v >> 8) & 0xFF, v & 0xFF))
            rows.append(bytes(row))
    write_png(os.path.join(GEN, "chamber_preview.png"), 512, 512, rows)
    print("mkchamber: %d tiles, cksum 0x%04X" % (len(tiles), ck))


if __name__ == "__main__":
    main()
