/* RIFT audio (D-020): SNESMOD glue. The soundbank is generated by
 * tools/audio/mkit.py -> smconv (sfx.it FIRST — spcLoadEffect indices),
 * asserted against the 58K ARAM budget at build time (INV-AUD-001).
 *
 * Load order mirrors pvsneslib's effectsandmusic example: load the module,
 * then (re)load every effect — spcLoad resets the ARAM layout, so effects
 * must be re-sent after it. track01.it carries the six SFX samples as its
 * own samples 1-6 too, so either spcLoadEffect indexing (soundbank-first-IT
 * or currently-loaded-module) lands the same sounds (D-020). */
#include <snes.h>
#include "src/audio/sound.h"
#include "src/data/generated/audio/soundbank.h"

extern char SOUNDBANK__;

#ifdef TEST_BUILD
extern u16 dbg_audio; /* dbg.asm +72: low8 ready, high8 last sfx id + 1 */
extern u16 dbg_sfx;   /* dbg.asm +74: sfx plays since boot */
#endif

static u8 audio_on;
static u8 sfx_grace; /* frames left with SFX suppressed: a fresh room load
                        re-grounds the player and would thud a phantom LAND
                        on every transition (probe-caught at boot, D-020) */

/* per-SFX spcEffect args (audio feel knobs live here, not tuning.h —
 * they are mix, not gameplay). pitch: 4 = 16kHz = mkit.py's native rate.
 * volpan = volume(0-15)*16 + pan(0-15, 8 = center). */
static const u8 sfx_pitch[6] = {4, 4, 4, 4, 4, 4};
static const u8 sfx_volpan[6] = {
    11 * 16 + 8, /* jump */
    12 * 16 + 8, /* fire */
    12 * 16 + 8, /* portal-open */
    13 * 16 + 8, /* teleport */
    10 * 16 + 8, /* land */
    15 * 16 + 8, /* death */
};

void audio_boot(void)
{
    audio_on = 0;
    spcBoot(); /* SPC700 handshake — interrupts must still be off */
}

static void load_effects(void)
{
    u8 i;
    for (i = 0; i < 6; i++)
        spcLoadEffect(i);
}

void audio_start(void)
{
    spcSetBank(&SOUNDBANK__);
    spcStop();
    spcLoad(MOD_SFX);
    load_effects();
    spcLoad(MOD_TRACK01);
    load_effects();
    spcSetModuleVolume(180);
    spcPlay(0);
    audio_on = 1;
    sfx_grace = 8;
#ifdef TEST_BUILD
    dbg_audio = 1;
#endif
}

void sfx_quiet(u8 frames)
{
    sfx_grace = frames;
}

void audio_frame(void)
{
    if (audio_on)
        spcProcess();
    if (sfx_grace)
        sfx_grace--;
}

void sfx_play(u8 id)
{
    if (!audio_on)
        return;
    if (sfx_grace)
        return;
    spcEffect(sfx_pitch[id], id, sfx_volpan[id]);
#ifdef TEST_BUILD
    dbg_sfx++;
    dbg_audio = (u16)(((u16)(id + 1) << 8) | (dbg_audio & 0x00FF));
#endif
}
