"""mklut.py — generated trig tables for the Mode 7 chamber math.

Emits src/data/generated/lut.asm: sin256 — 256 s16 entries, 8.8 fixed point,
sin(i * 2pi / 256) * 256, little-endian. cos(i) = sin256[(i + 64) & 255].
Deterministic (round-half-away-from-zero, pure integer output).
"""
import math
import os

GEN = os.path.join(os.path.dirname(__file__), "..", "src", "data", "generated")


def main():
    os.makedirs(GEN, exist_ok=True)
    vals = []
    for i in range(256):
        v = math.sin(i * 2.0 * math.pi / 256.0) * 256.0
        vals.append(int(math.floor(v + 0.5)) if v >= 0 else -int(math.floor(-v + 0.5)))
    with open(os.path.join(GEN, "lut.asm"), "w", newline="\n") as f:
        f.write('.include "hdr.asm"\n\n')
        f.write("; GENERATED by tools/mklut.py — never hand-edit.\n")
        f.write("; sin256: 256 x s16 (8.8), sin(i*2pi/256)*256; cos = sin256[(i+64)&255]\n")
        f.write('.section ".lut" superfree\n')
        f.write("sin256:\n")
        for i in range(0, 256, 8):
            f.write(".dw " + ", ".join(str(v & 0xFFFF) for v in vals[i:i + 8]) + "\n")
        f.write(".ends\n")
    print("mklut: sin256 written")


if __name__ == "__main__":
    main()
