"""roomglue.py — bake tmx2snes outputs into skyfell's room ROM data.

For every src/data/generated/maps/<room>.m16 (+ .b16/.t16 beside it):
  - verifies the .t16 remap is IDENTITY (our tileset is authored, never
    deduped — a non-identity remap means the pipeline drifted)
  - bakes palette/priority (.t16) into each .m16 map word, keeping flips:
    final = t16[tile] | (m16word & 0xC000)
  - emits <room>.map.bin (baked u16 words, row-major, header stripped) and
    <room>.att.bin (attribute u16 per tile id, padded to 32 entries)
  - computes the INV-ENG-005 checksum: u16 wraparound sum of every baked map
    word + every attribute word
Then writes rooms.asm (superfree sections, one per room — a wla section must
fit one 32KB bank) and rooms.h (dims + checksum + extern-label docs).
Deterministic: byte-identical outputs for identical inputs.
"""
import glob
import json
import os
import struct

ROOT = os.path.join(os.path.dirname(__file__), "..")
GEN = os.path.join(ROOT, "src", "data", "generated")
MAPS = os.path.join(GEN, "maps")

ATTR_PAD = 64  # attr table entries in ROM (tile ids must stay below this)


def bake(m16_path):
    room = os.path.splitext(os.path.basename(m16_path))[0]
    base = os.path.splitext(m16_path)[0]
    with open(m16_path, "rb") as f:
        raw = f.read()
    w_px, h_px, nbytes = struct.unpack_from("<3H", raw, 0)
    w, h = w_px // 8, h_px // 8
    words = list(struct.unpack_from("<%dH" % (nbytes // 2), raw, 6))
    assert len(words) == w * h, (room, w, h, len(words))

    with open(base + ".t16", "rb") as f:
        t16raw = f.read()
    t16 = list(struct.unpack("<%dH" % (len(t16raw) // 2), t16raw))
    for i, t in enumerate(t16):
        assert (t & 0x3FF) == i, "%s: .t16 remap not identity at %d (0x%04X)" % (room, i, t)

    with open(base + ".b16", "rb") as f:
        b16raw = f.read()
    attrs = list(struct.unpack("<%dH" % (len(b16raw) // 2), b16raw))
    assert len(attrs) <= ATTR_PAD, "%s: %d tiles > ATTR_PAD %d" % (room, len(attrs), ATTR_PAD)
    attrs += [0] * (ATTR_PAD - len(attrs))

    baked = [t16[wd & 0x3FF] | (wd & 0xC000) for wd in words]

    ck = 0
    for v in baked:
        ck = (ck + v) & 0xFFFF
    for v in attrs:
        ck = (ck + v) & 0xFFFF

    with open(base + ".map.bin", "wb") as f:
        f.write(struct.pack("<%dH" % len(baked), *baked))
    with open(base + ".att.bin", "wb") as f:
        f.write(struct.pack("<%dH" % len(attrs), *attrs))
    return {"name": room, "w": w, "h": h, "cksum": ck}


def room_id(name):
    """D-021 id rule: room01 -> 0, the chamber = 1 (reserved), roomNN -> NN."""
    if name == "chamber":
        return 1
    assert name.startswith("room"), name
    n = int(name[4:])
    assert n != 1 or name == "room01", name
    rid = 0 if n == 1 else n
    assert rid != 1, "%s: room id 1 is the chamber (D-021)" % name
    return rid


SPAWN_KINDS = {"crate": 0, "sentry_l": 1, "sentry_r": 2}


def write_roomtabs(rooms):
    """roomtabs.h (D-021): entry/door/spawn tables generated from the
    @-headers in assets/maps (mkmaps' .meta.json sidecars). Guarded halves
    so each consumer gets exactly one ROM copy: ROOMTABS_MAIN (main.c —
    entries + doors), ROOMTABS_ENT (entity.c — spawns)."""
    metas = {}
    for r in rooms:
        with open(os.path.join(MAPS, r["name"] + ".meta.json")) as f:
            metas[r["name"]] = json.load(f)
    ids = {r["name"]: room_id(r["name"]) for r in rooms}
    known = set(ids) | {"chamber"}
    max_id = max(ids.values())

    entries = {}
    doors = []
    spawns = []
    for r in rooms:
        name = r["name"]
        m = metas[name]
        entries[ids[name]] = (m["entry"][0], m["entry"][1], name)
        for d in m["doors"]:
            assert d["dest"] in known, "%s: door to unknown room %s" % (name, d["dest"])
            dest = 1 if d["dest"] == "chamber" else ids[d["dest"]]
            doors.append((ids[name],) + tuple(d["rect"]) + (dest, d["x"], d["y"], name, d["dest"]))
        for s in m["spawns"]:
            spawns.append((ids[name], SPAWN_KINDS[s["kind"]], s["x"], s["y"], name, s["kind"]))

    with open(os.path.join(GEN, "roomtabs.h"), "w", newline="\n") as f:
        f.write("/* GENERATED by tools/roomglue.py from assets/maps @-headers (D-021)\n")
        f.write(" * — never hand-edit. Define ROOMTABS_MAIN or ROOMTABS_ENT before\n")
        f.write(" * including so each table lands in exactly one translation unit. */\n")
        f.write("#ifndef GEN_ROOMTABS_H\n#define GEN_ROOMTABS_H\n\n")
        f.write("#define RT_ROOM_MAX %d\n\n" % max_id)
        f.write("#ifdef ROOMTABS_MAIN\n")
        f.write("/* per-room entry px (box top-left), indexed by room id; id 1 (the\n")
        f.write(" * chamber) and unauthored ids fall back to room01's entry */\n")
        f.write("static const u16 rt_entry[RT_ROOM_MAX + 1][2] = {\n")
        fb = entries[0]
        for i in range(max_id + 1):
            x, y, who = entries.get(i, (fb[0], fb[1], "fallback: room01"))
            if i == 1:
                x, y, who = fb[0], fb[1], "the chamber (unused)"
            f.write("    {%d, %d}, /* %d: %s */\n" % (x, y, i, who))
        f.write("};\n\n")
        f.write("/* {room, x0, x1, y0, y1, target, entry x, entry y} — px, inclusive */\n")
        f.write("#define RT_DOOR_N %d\n" % len(doors))
        f.write("static const u16 rt_door[RT_DOOR_N][8] = {\n")
        for d in doors:
            f.write("    {%d, %d, %d, %d, %d, %d, %d, %d}, /* %s -> %s */\n" % d)
        f.write("};\n")
        f.write("#endif /* ROOMTABS_MAIN */\n\n")
        f.write("#ifdef ROOMTABS_ENT\n")
        f.write("#define RTS_CRATE 0\n#define RTS_SENTRY_L 1\n#define RTS_SENTRY_R 2\n")
        f.write("#define RT_SPAWN_N %d\n" % len(spawns))
        f.write("/* {room, kind, x, y} */\n")
        f.write("static const u16 rt_spawn[RT_SPAWN_N][4] = {\n")
        for s in spawns:
            f.write("    {%d, %d, %d, %d}, /* %s: %s */\n" % s)
        f.write("};\n")
        f.write("#endif /* ROOMTABS_ENT */\n\n")
        f.write("#endif\n")
    print("roomglue: roomtabs.h — %d entries, %d doors, %d spawns"
          % (len(entries), len(doors), len(spawns)))


def main():
    rooms = [bake(p) for p in sorted(glob.glob(os.path.join(MAPS, "*.m16")))]
    assert rooms, "no maps/*.m16 — did tmx2snes run?"

    # HOT-PATH CONTRACT (D-016): every collision reader indexes room01_att —
    # all rooms must share ONE tileset, so every att table must be
    # byte-identical. A drift here means a second tileset arrived without
    # the runtime growing an att story.
    ref = open(os.path.join(MAPS, rooms[0]["name"] + ".att.bin"), "rb").read()
    for r in rooms[1:]:
        cur = open(os.path.join(MAPS, r["name"] + ".att.bin"), "rb").read()
        assert cur == ref, (
            "%s: att table differs from %s — rooms must share the tileset "
            "(hot paths index room01_att; see D-016)" % (r["name"], rooms[0]["name"]))

    with open(os.path.join(GEN, "rooms.asm"), "w", newline="\n") as f:
        f.write('.include "hdr.asm"\n\n')
        f.write("; GENERATED by tools/roomglue.py — never hand-edit (CLAUDE.md).\n")
        f.write("; Baked room data (D-012): map words with palette/priority folded in,\n")
        f.write("; + per-tile attribute table. One superfree section per room (32KB law).\n")
        for r in rooms:
            f.write('\n.section ".room_%s" superfree\n' % r["name"])
            f.write("%s_map:\n.incbin \"src/data/generated/maps/%s.map.bin\"\n" % (r["name"], r["name"]))
            f.write("%s_att:\n.incbin \"src/data/generated/maps/%s.att.bin\"\n" % (r["name"], r["name"]))
            f.write(".ends\n")

    write_roomtabs(rooms)

    with open(os.path.join(GEN, "rooms.h"), "w", newline="\n") as f:
        f.write("/* GENERATED by tools/roomglue.py — never hand-edit. */\n")
        f.write("#ifndef GEN_ROOMS_H\n#define GEN_ROOMS_H\n\n")
        f.write("#define ROOM_COUNT %d\n" % len(rooms))
        f.write("#define ROOM_ATTR_PAD %d\n\n" % ATTR_PAD)
        for i, r in enumerate(rooms):
            up = r["name"].upper()
            f.write("/* room %d: %s — extern u16 %s_map[], %s_att[] (rooms.asm) */\n"
                    % (i, r["name"], r["name"], r["name"]))
            f.write("#define %s_W %d\n#define %s_H %d\n#define %s_CKSUM 0x%04X\n\n"
                    % (up, r["w"], up, r["h"], up, r["cksum"]))
        f.write("#endif\n")

    for r in rooms:
        print("roomglue: %s %dx%d cksum 0x%04X" % (r["name"], r["w"], r["h"], r["cksum"]))


if __name__ == "__main__":
    main()
