"""roomglue.py — bake tmx2snes outputs into skyfell's room ROM data.

For every src/data/generated/maps/<room>.m16 (+ .b16/.t16 beside it):
  - verifies the .t16 remap is IDENTITY (our tileset is authored, never
    deduped — a non-identity remap means the pipeline drifted)
  - bakes palette/priority (.t16) into each .m16 map word, keeping flips:
    final = t16[tile] | (m16word & 0xC000)
  - emits <room>.map.bin (baked u16 words, row-major, header stripped) and
    <room>.att.bin (attribute u16 per tile id, padded to 32 entries)
  - computes the INV-ENG-005 checksum: u16 wraparound sum of every baked map
    word + every attribute word
Then writes rooms.asm (superfree sections, one per room — a wla section must
fit one 32KB bank) and rooms.h (dims + checksum + extern-label docs).
Deterministic: byte-identical outputs for identical inputs.
"""
import glob
import os
import struct

ROOT = os.path.join(os.path.dirname(__file__), "..")
GEN = os.path.join(ROOT, "src", "data", "generated")
MAPS = os.path.join(GEN, "maps")

ATTR_PAD = 64  # attr table entries in ROM (tile ids must stay below this)


def bake(m16_path):
    room = os.path.splitext(os.path.basename(m16_path))[0]
    base = os.path.splitext(m16_path)[0]
    with open(m16_path, "rb") as f:
        raw = f.read()
    w_px, h_px, nbytes = struct.unpack_from("<3H", raw, 0)
    w, h = w_px // 8, h_px // 8
    words = list(struct.unpack_from("<%dH" % (nbytes // 2), raw, 6))
    assert len(words) == w * h, (room, w, h, len(words))

    with open(base + ".t16", "rb") as f:
        t16raw = f.read()
    t16 = list(struct.unpack("<%dH" % (len(t16raw) // 2), t16raw))
    for i, t in enumerate(t16):
        assert (t & 0x3FF) == i, "%s: .t16 remap not identity at %d (0x%04X)" % (room, i, t)

    with open(base + ".b16", "rb") as f:
        b16raw = f.read()
    attrs = list(struct.unpack("<%dH" % (len(b16raw) // 2), b16raw))
    assert len(attrs) <= ATTR_PAD, "%s: %d tiles > ATTR_PAD %d" % (room, len(attrs), ATTR_PAD)
    attrs += [0] * (ATTR_PAD - len(attrs))

    baked = [t16[wd & 0x3FF] | (wd & 0xC000) for wd in words]

    ck = 0
    for v in baked:
        ck = (ck + v) & 0xFFFF
    for v in attrs:
        ck = (ck + v) & 0xFFFF

    with open(base + ".map.bin", "wb") as f:
        f.write(struct.pack("<%dH" % len(baked), *baked))
    with open(base + ".att.bin", "wb") as f:
        f.write(struct.pack("<%dH" % len(attrs), *attrs))
    return {"name": room, "w": w, "h": h, "cksum": ck}


def main():
    rooms = [bake(p) for p in sorted(glob.glob(os.path.join(MAPS, "*.m16")))]
    assert rooms, "no maps/*.m16 — did tmx2snes run?"

    with open(os.path.join(GEN, "rooms.asm"), "w", newline="\n") as f:
        f.write('.include "hdr.asm"\n\n')
        f.write("; GENERATED by tools/roomglue.py — never hand-edit (CLAUDE.md).\n")
        f.write("; Baked room data (D-012): map words with palette/priority folded in,\n")
        f.write("; + per-tile attribute table. One superfree section per room (32KB law).\n")
        for r in rooms:
            f.write('\n.section ".room_%s" superfree\n' % r["name"])
            f.write("%s_map:\n.incbin \"src/data/generated/maps/%s.map.bin\"\n" % (r["name"], r["name"]))
            f.write("%s_att:\n.incbin \"src/data/generated/maps/%s.att.bin\"\n" % (r["name"], r["name"]))
            f.write(".ends\n")

    with open(os.path.join(GEN, "rooms.h"), "w", newline="\n") as f:
        f.write("/* GENERATED by tools/roomglue.py — never hand-edit. */\n")
        f.write("#ifndef GEN_ROOMS_H\n#define GEN_ROOMS_H\n\n")
        f.write("#define ROOM_COUNT %d\n" % len(rooms))
        f.write("#define ROOM_ATTR_PAD %d\n\n" % ATTR_PAD)
        for i, r in enumerate(rooms):
            up = r["name"].upper()
            f.write("/* room %d: %s — extern u16 %s_map[], %s_att[] (rooms.asm) */\n"
                    % (i, r["name"], r["name"], r["name"]))
            f.write("#define %s_W %d\n#define %s_H %d\n#define %s_CKSUM 0x%04X\n\n"
                    % (up, r["w"], up, r["h"], up, r["cksum"]))
        f.write("#endif\n")

    for r in rooms:
        print("roomglue: %s %dx%d cksum 0x%04X" % (r["name"], r["w"], r["h"], r["cksum"]))


if __name__ == "__main__":
    main()
